const COMMENT_LENGTH_MIN = 5
const COMMENT_LENGTH_MAX = 280
const TOPIC_NAME_LENGTH_MIN = 3
const TOPIC_NAME_LENGTH_MAX = 32

const USER_THEME_TOKEN_LENGTH = 21
const THEME_NAME_MIN_LENGTH = 4
const THEME_NAME_MAX_LENGTH = 20

const USER_LOGIN_MIN_LENGTH = 3
const USER_LOGIN_MAX_LENGTH = 20

export {
  COMMENT_LENGTH_MAX,
  COMMENT_LENGTH_MIN,
  THEME_NAME_MAX_LENGTH,
  THEME_NAME_MIN_LENGTH,
  TOPIC_NAME_LENGTH_MAX,
  TOPIC_NAME_LENGTH_MIN,
  USER_LOGIN_MAX_LENGTH,
  USER_LOGIN_MIN_LENGTH,
  USER_THEME_TOKEN_LENGTH,
}
