const COMMENT_LENGTH_MIN = 5
const COMMENT_LENGTH_MAX = 280
const TOPIC_NAME_LENGTH_MIN = 3
const TOPIC_NAME_LENGTH_MAX = 32

export {
  COMMENT_LENGTH_MIN,
  COMMENT_LENGTH_MAX,
  TOPIC_NAME_LENGTH_MIN,
  TOPIC_NAME_LENGTH_MAX,
}
